{{- if and (.Values.autoscaling.enabled) (eq .Values.autoscaling.mode "hpa") }}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: {{ template "fullname" . }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
{{ include "app.commonlabels" . | indent 4 }}
  name: {{ template "fullname" . }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "fullname" . }}
  minReplicas: {{ .Values.autoscaling.hpa.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.hpa.maxReplicas }}
{{- with .Values.autoscaling.hpa.behavior }}
  behavior:
{{ toYaml . | indent 4 }}
{{- end }}
  metrics:
{{- with .Values.autoscaling.hpa.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ . }}
{{- end }}
{{- with .Values.autoscaling.hpa.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ . }}
{{- end }}
{{- with .Values.autoscaling.hpa.customMetrics }}
{{ toYaml . | indent 4 }}
{{- end }}
{{- end }}
