{{- if and (.Values.autoscaling.enabled) (eq .Values.autoscaling.mode "vpa") }}
apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  labels:
    app: {{ template "fullname" . }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
{{ include "app.commonlabels" . | indent 4 }}
  name: {{ template "fullname" . }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "fullname" . }}
  updatePolicy:
    updateMode: '{{ .Values.autoscaling.vpa.updateMode }}'
{{- end }}
